server :\
 ./protobuf/createVote.pb.cc\
 ./protobuf/createVoteResponse.pb.cc\
 ./protobuf/loginRequest.pb.cc\
 ./protobuf/loginResponse.pb.cc\
 ./protobuf/vote.pb.cc\
 ./protobuf/voteResponse.pb.cc\
 ./protobuf/getAllVotes.pb.cc\
 ./protobuf/getAllVotesResponse.pb.cc\
 ./protobuf/getVoteResultByOneJudge.pb.cc\
 ./protobuf/getVoteResultByOneJudgeResponse.pb.cc\
 ./protobuf/getVoteResult.pb.cc\
 ./log/log.cpp\
 ./voteserver/service.cpp\
 ./vote/vote.cpp\
 ./config.cpp\
 ./main.cpp

	g++ -g \
 ./protobuf/createVote.pb.cc\
 ./protobuf/createVoteResponse.pb.cc\
 ./protobuf/loginRequest.pb.cc\
 ./protobuf/loginResponse.pb.cc\
 ./protobuf/vote.pb.cc\
 ./protobuf/voteResponse.pb.cc\
 ./protobuf/getAllVotes.pb.cc\
 ./protobuf/getAllVotesResponse.pb.cc\
 ./protobuf/getVoteResultByOneJudge.pb.cc\
 ./protobuf/getVoteResultByOneJudgeResponse.pb.cc\
 ./protobuf/getVoteResult.pb.cc\
 ./log/log.cpp\
 ./voteserver/service.cpp\
 ./vote/vote.cpp\
 ./config.cpp\
 ./main.cpp\
 -l pthread -l protobuf -o server