// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: createVote.proto

#include "createVote.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_createVote_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_createVote_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_CreateVote_Judge;
}  // namespace protobuf_createVote_2eproto
namespace protoMsg {
class CreateVote_JudgeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CreateVote_Judge>
      _instance;
} _CreateVote_Judge_default_instance_;
class CreateVoteDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<CreateVote>
      _instance;
} _CreateVote_default_instance_;
}  // namespace protoMsg
namespace protobuf_createVote_2eproto {
static void InitDefaultsCreateVote_Judge() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_CreateVote_Judge_default_instance_;
    new (ptr) ::protoMsg::CreateVote_Judge();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::CreateVote_Judge::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_CreateVote_Judge =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCreateVote_Judge}, {}};

static void InitDefaultsCreateVote() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_CreateVote_default_instance_;
    new (ptr) ::protoMsg::CreateVote();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::CreateVote::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_CreateVote =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCreateVote}, {
      &protobuf_createVote_2eproto::scc_info_CreateVote_Judge.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_CreateVote_Judge.base);
  ::google::protobuf::internal::InitSCC(&scc_info_CreateVote.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote_Judge, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote_Judge, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote_Judge, id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, votename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, dazhongweight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, zhuanyeweight_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, judgechoose_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, playerchoose_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::CreateVote, deadline_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protoMsg::CreateVote_Judge)},
  { 7, -1, sizeof(::protoMsg::CreateVote)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_CreateVote_Judge_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_CreateVote_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "createVote.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020createVote.proto\022\010protoMsg\"\326\001\n\nCreateV"
      "ote\022\014\n\004type\030\001 \001(\t\022\020\n\010voteName\030\002 \001(\t\022\025\n\rd"
      "azhongWeight\030\003 \001(\t\022\025\n\rzhuanyeWeight\030\004 \001("
      "\t\022/\n\013judgeChoose\030\005 \003(\0132\032.protoMsg.Create"
      "Vote.Judge\022\024\n\014playerChoose\030\006 \003(\t\022\020\n\010dead"
      "line\030\007 \001(\t\032!\n\005Judge\022\014\n\004name\030\001 \001(\t\022\n\n\002ID\030"
      "\002 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 253);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "createVote.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_createVote_2eproto
namespace protoMsg {

// ===================================================================

void CreateVote_Judge::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CreateVote_Judge::kNameFieldNumber;
const int CreateVote_Judge::kIDFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CreateVote_Judge::CreateVote_Judge()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_createVote_2eproto::scc_info_CreateVote_Judge.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.CreateVote.Judge)
}
CreateVote_Judge::CreateVote_Judge(const CreateVote_Judge& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.id().size() > 0) {
    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  // @@protoc_insertion_point(copy_constructor:protoMsg.CreateVote.Judge)
}

void CreateVote_Judge::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CreateVote_Judge::~CreateVote_Judge() {
  // @@protoc_insertion_point(destructor:protoMsg.CreateVote.Judge)
  SharedDtor();
}

void CreateVote_Judge::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CreateVote_Judge::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CreateVote_Judge::descriptor() {
  ::protobuf_createVote_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_createVote_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CreateVote_Judge& CreateVote_Judge::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_createVote_2eproto::scc_info_CreateVote_Judge.base);
  return *internal_default_instance();
}


void CreateVote_Judge::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.CreateVote.Judge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool CreateVote_Judge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.CreateVote.Judge)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.Judge.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string ID = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id().data(), static_cast<int>(this->id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.Judge.ID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.CreateVote.Judge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.CreateVote.Judge)
  return false;
#undef DO_
}

void CreateVote_Judge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.CreateVote.Judge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.Judge.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string ID = 2;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.Judge.ID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.CreateVote.Judge)
}

::google::protobuf::uint8* CreateVote_Judge::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.CreateVote.Judge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.Judge.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string ID = 2;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), static_cast<int>(this->id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.Judge.ID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.CreateVote.Judge)
  return target;
}

size_t CreateVote_Judge::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.CreateVote.Judge)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string ID = 2;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateVote_Judge::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.CreateVote.Judge)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateVote_Judge* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CreateVote_Judge>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.CreateVote.Judge)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.CreateVote.Judge)
    MergeFrom(*source);
  }
}

void CreateVote_Judge::MergeFrom(const CreateVote_Judge& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.CreateVote.Judge)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.id().size() > 0) {

    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
}

void CreateVote_Judge::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.CreateVote.Judge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateVote_Judge::CopyFrom(const CreateVote_Judge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.CreateVote.Judge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateVote_Judge::IsInitialized() const {
  return true;
}

void CreateVote_Judge::Swap(CreateVote_Judge* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CreateVote_Judge::InternalSwap(CreateVote_Judge* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  id_.Swap(&other->id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CreateVote_Judge::GetMetadata() const {
  protobuf_createVote_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_createVote_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void CreateVote::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int CreateVote::kTypeFieldNumber;
const int CreateVote::kVoteNameFieldNumber;
const int CreateVote::kDazhongWeightFieldNumber;
const int CreateVote::kZhuanyeWeightFieldNumber;
const int CreateVote::kJudgeChooseFieldNumber;
const int CreateVote::kPlayerChooseFieldNumber;
const int CreateVote::kDeadlineFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

CreateVote::CreateVote()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_createVote_2eproto::scc_info_CreateVote.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.CreateVote)
}
CreateVote::CreateVote(const CreateVote& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      judgechoose_(from.judgechoose_),
      playerchoose_(from.playerchoose_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  votename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.votename().size() > 0) {
    votename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.votename_);
  }
  dazhongweight_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.dazhongweight().size() > 0) {
    dazhongweight_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dazhongweight_);
  }
  zhuanyeweight_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.zhuanyeweight().size() > 0) {
    zhuanyeweight_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.zhuanyeweight_);
  }
  deadline_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.deadline().size() > 0) {
    deadline_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deadline_);
  }
  // @@protoc_insertion_point(copy_constructor:protoMsg.CreateVote)
}

void CreateVote::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  votename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dazhongweight_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  zhuanyeweight_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deadline_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

CreateVote::~CreateVote() {
  // @@protoc_insertion_point(destructor:protoMsg.CreateVote)
  SharedDtor();
}

void CreateVote::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  votename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dazhongweight_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  zhuanyeweight_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deadline_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void CreateVote::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* CreateVote::descriptor() {
  ::protobuf_createVote_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_createVote_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const CreateVote& CreateVote::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_createVote_2eproto::scc_info_CreateVote.base);
  return *internal_default_instance();
}


void CreateVote::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.CreateVote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  judgechoose_.Clear();
  playerchoose_.Clear();
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  votename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dazhongweight_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  zhuanyeweight_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  deadline_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool CreateVote::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.CreateVote)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string voteName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_votename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->votename().data(), static_cast<int>(this->votename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.voteName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string dazhongWeight = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dazhongweight()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dazhongweight().data(), static_cast<int>(this->dazhongweight().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.dazhongWeight"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string zhuanyeWeight = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_zhuanyeweight()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->zhuanyeweight().data(), static_cast<int>(this->zhuanyeweight().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.zhuanyeWeight"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .protoMsg.CreateVote.Judge judgeChoose = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_judgechoose()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string playerChoose = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_playerchoose()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->playerchoose(this->playerchoose_size() - 1).data(),
            static_cast<int>(this->playerchoose(this->playerchoose_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.playerChoose"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string deadline = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_deadline()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->deadline().data(), static_cast<int>(this->deadline().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.CreateVote.deadline"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.CreateVote)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.CreateVote)
  return false;
#undef DO_
}

void CreateVote::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.CreateVote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // string voteName = 2;
  if (this->votename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->votename().data(), static_cast<int>(this->votename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.voteName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->votename(), output);
  }

  // string dazhongWeight = 3;
  if (this->dazhongweight().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dazhongweight().data(), static_cast<int>(this->dazhongweight().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.dazhongWeight");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->dazhongweight(), output);
  }

  // string zhuanyeWeight = 4;
  if (this->zhuanyeweight().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->zhuanyeweight().data(), static_cast<int>(this->zhuanyeweight().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.zhuanyeWeight");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->zhuanyeweight(), output);
  }

  // repeated .protoMsg.CreateVote.Judge judgeChoose = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->judgechoose_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->judgechoose(static_cast<int>(i)),
      output);
  }

  // repeated string playerChoose = 6;
  for (int i = 0, n = this->playerchoose_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->playerchoose(i).data(), static_cast<int>(this->playerchoose(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.playerChoose");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->playerchoose(i), output);
  }

  // string deadline = 7;
  if (this->deadline().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deadline().data(), static_cast<int>(this->deadline().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.deadline");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->deadline(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.CreateVote)
}

::google::protobuf::uint8* CreateVote::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.CreateVote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // string voteName = 2;
  if (this->votename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->votename().data(), static_cast<int>(this->votename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.voteName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->votename(), target);
  }

  // string dazhongWeight = 3;
  if (this->dazhongweight().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dazhongweight().data(), static_cast<int>(this->dazhongweight().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.dazhongWeight");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->dazhongweight(), target);
  }

  // string zhuanyeWeight = 4;
  if (this->zhuanyeweight().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->zhuanyeweight().data(), static_cast<int>(this->zhuanyeweight().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.zhuanyeWeight");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->zhuanyeweight(), target);
  }

  // repeated .protoMsg.CreateVote.Judge judgeChoose = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->judgechoose_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->judgechoose(static_cast<int>(i)), deterministic, target);
  }

  // repeated string playerChoose = 6;
  for (int i = 0, n = this->playerchoose_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->playerchoose(i).data(), static_cast<int>(this->playerchoose(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.playerChoose");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(6, this->playerchoose(i), target);
  }

  // string deadline = 7;
  if (this->deadline().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->deadline().data(), static_cast<int>(this->deadline().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.CreateVote.deadline");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->deadline(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.CreateVote)
  return target;
}

size_t CreateVote::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.CreateVote)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .protoMsg.CreateVote.Judge judgeChoose = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->judgechoose_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->judgechoose(static_cast<int>(i)));
    }
  }

  // repeated string playerChoose = 6;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->playerchoose_size());
  for (int i = 0, n = this->playerchoose_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->playerchoose(i));
  }

  // string type = 1;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // string voteName = 2;
  if (this->votename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->votename());
  }

  // string dazhongWeight = 3;
  if (this->dazhongweight().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->dazhongweight());
  }

  // string zhuanyeWeight = 4;
  if (this->zhuanyeweight().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->zhuanyeweight());
  }

  // string deadline = 7;
  if (this->deadline().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->deadline());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CreateVote::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.CreateVote)
  GOOGLE_DCHECK_NE(&from, this);
  const CreateVote* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const CreateVote>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.CreateVote)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.CreateVote)
    MergeFrom(*source);
  }
}

void CreateVote::MergeFrom(const CreateVote& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.CreateVote)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  judgechoose_.MergeFrom(from.judgechoose_);
  playerchoose_.MergeFrom(from.playerchoose_);
  if (from.type().size() > 0) {

    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  if (from.votename().size() > 0) {

    votename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.votename_);
  }
  if (from.dazhongweight().size() > 0) {

    dazhongweight_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dazhongweight_);
  }
  if (from.zhuanyeweight().size() > 0) {

    zhuanyeweight_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.zhuanyeweight_);
  }
  if (from.deadline().size() > 0) {

    deadline_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.deadline_);
  }
}

void CreateVote::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.CreateVote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CreateVote::CopyFrom(const CreateVote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.CreateVote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CreateVote::IsInitialized() const {
  return true;
}

void CreateVote::Swap(CreateVote* other) {
  if (other == this) return;
  InternalSwap(other);
}
void CreateVote::InternalSwap(CreateVote* other) {
  using std::swap;
  CastToBase(&judgechoose_)->InternalSwap(CastToBase(&other->judgechoose_));
  playerchoose_.InternalSwap(CastToBase(&other->playerchoose_));
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  votename_.Swap(&other->votename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  dazhongweight_.Swap(&other->dazhongweight_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  zhuanyeweight_.Swap(&other->zhuanyeweight_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  deadline_.Swap(&other->deadline_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata CreateVote::GetMetadata() const {
  protobuf_createVote_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_createVote_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protoMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::CreateVote_Judge* Arena::CreateMaybeMessage< ::protoMsg::CreateVote_Judge >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::CreateVote_Judge >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::CreateVote* Arena::CreateMaybeMessage< ::protoMsg::CreateVote >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::CreateVote >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
