// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getAllVotesResponse.proto

#include "getAllVotesResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_getAllVotesResponse_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_getAllVotesResponse_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GetAllVotesResponse_Vote;
}  // namespace protobuf_getAllVotesResponse_2eproto
namespace protoMsg {
class GetAllVotesResponse_VoteDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetAllVotesResponse_Vote>
      _instance;
} _GetAllVotesResponse_Vote_default_instance_;
class GetAllVotesResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetAllVotesResponse>
      _instance;
} _GetAllVotesResponse_default_instance_;
}  // namespace protoMsg
namespace protobuf_getAllVotesResponse_2eproto {
static void InitDefaultsGetAllVotesResponse_Vote() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_GetAllVotesResponse_Vote_default_instance_;
    new (ptr) ::protoMsg::GetAllVotesResponse_Vote();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::GetAllVotesResponse_Vote::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetAllVotesResponse_Vote =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetAllVotesResponse_Vote}, {}};

static void InitDefaultsGetAllVotesResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_GetAllVotesResponse_default_instance_;
    new (ptr) ::protoMsg::GetAllVotesResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::GetAllVotesResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GetAllVotesResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGetAllVotesResponse}, {
      &protobuf_getAllVotesResponse_2eproto::scc_info_GetAllVotesResponse_Vote.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GetAllVotesResponse_Vote.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetAllVotesResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetAllVotesResponse_Vote, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetAllVotesResponse_Vote, votename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetAllVotesResponse_Vote, voteid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetAllVotesResponse_Vote, isvalid_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetAllVotesResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetAllVotesResponse, votes_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protoMsg::GetAllVotesResponse_Vote)},
  { 8, -1, sizeof(::protoMsg::GetAllVotesResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_GetAllVotesResponse_Vote_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_GetAllVotesResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "getAllVotesResponse.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\031getAllVotesResponse.proto\022\010protoMsg\"\203\001"
      "\n\023GetAllVotesResponse\0221\n\005votes\030\001 \003(\0132\".p"
      "rotoMsg.GetAllVotesResponse.Vote\0329\n\004Vote"
      "\022\020\n\010voteName\030\001 \001(\t\022\016\n\006voteID\030\002 \001(\t\022\017\n\007is"
      "Valid\030\003 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 179);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "getAllVotesResponse.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_getAllVotesResponse_2eproto
namespace protoMsg {

// ===================================================================

void GetAllVotesResponse_Vote::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetAllVotesResponse_Vote::kVoteNameFieldNumber;
const int GetAllVotesResponse_Vote::kVoteIDFieldNumber;
const int GetAllVotesResponse_Vote::kIsValidFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetAllVotesResponse_Vote::GetAllVotesResponse_Vote()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_getAllVotesResponse_2eproto::scc_info_GetAllVotesResponse_Vote.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.GetAllVotesResponse.Vote)
}
GetAllVotesResponse_Vote::GetAllVotesResponse_Vote(const GetAllVotesResponse_Vote& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  votename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.votename().size() > 0) {
    votename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.votename_);
  }
  voteid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.voteid().size() > 0) {
    voteid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.voteid_);
  }
  isvalid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.isvalid().size() > 0) {
    isvalid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.isvalid_);
  }
  // @@protoc_insertion_point(copy_constructor:protoMsg.GetAllVotesResponse.Vote)
}

void GetAllVotesResponse_Vote::SharedCtor() {
  votename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  voteid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvalid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetAllVotesResponse_Vote::~GetAllVotesResponse_Vote() {
  // @@protoc_insertion_point(destructor:protoMsg.GetAllVotesResponse.Vote)
  SharedDtor();
}

void GetAllVotesResponse_Vote::SharedDtor() {
  votename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  voteid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvalid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetAllVotesResponse_Vote::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetAllVotesResponse_Vote::descriptor() {
  ::protobuf_getAllVotesResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getAllVotesResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetAllVotesResponse_Vote& GetAllVotesResponse_Vote::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_getAllVotesResponse_2eproto::scc_info_GetAllVotesResponse_Vote.base);
  return *internal_default_instance();
}


void GetAllVotesResponse_Vote::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.GetAllVotesResponse.Vote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  votename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  voteid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvalid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetAllVotesResponse_Vote::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.GetAllVotesResponse.Vote)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string voteName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_votename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->votename().data(), static_cast<int>(this->votename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetAllVotesResponse.Vote.voteName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string voteID = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_voteid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->voteid().data(), static_cast<int>(this->voteid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetAllVotesResponse.Vote.voteID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string isValid = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_isvalid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->isvalid().data(), static_cast<int>(this->isvalid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetAllVotesResponse.Vote.isValid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.GetAllVotesResponse.Vote)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.GetAllVotesResponse.Vote)
  return false;
#undef DO_
}

void GetAllVotesResponse_Vote::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.GetAllVotesResponse.Vote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string voteName = 1;
  if (this->votename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->votename().data(), static_cast<int>(this->votename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetAllVotesResponse.Vote.voteName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->votename(), output);
  }

  // string voteID = 2;
  if (this->voteid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->voteid().data(), static_cast<int>(this->voteid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetAllVotesResponse.Vote.voteID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->voteid(), output);
  }

  // string isValid = 3;
  if (this->isvalid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->isvalid().data(), static_cast<int>(this->isvalid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetAllVotesResponse.Vote.isValid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->isvalid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.GetAllVotesResponse.Vote)
}

::google::protobuf::uint8* GetAllVotesResponse_Vote::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.GetAllVotesResponse.Vote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string voteName = 1;
  if (this->votename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->votename().data(), static_cast<int>(this->votename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetAllVotesResponse.Vote.voteName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->votename(), target);
  }

  // string voteID = 2;
  if (this->voteid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->voteid().data(), static_cast<int>(this->voteid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetAllVotesResponse.Vote.voteID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->voteid(), target);
  }

  // string isValid = 3;
  if (this->isvalid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->isvalid().data(), static_cast<int>(this->isvalid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetAllVotesResponse.Vote.isValid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->isvalid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.GetAllVotesResponse.Vote)
  return target;
}

size_t GetAllVotesResponse_Vote::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.GetAllVotesResponse.Vote)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string voteName = 1;
  if (this->votename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->votename());
  }

  // string voteID = 2;
  if (this->voteid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->voteid());
  }

  // string isValid = 3;
  if (this->isvalid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->isvalid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetAllVotesResponse_Vote::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.GetAllVotesResponse.Vote)
  GOOGLE_DCHECK_NE(&from, this);
  const GetAllVotesResponse_Vote* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetAllVotesResponse_Vote>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.GetAllVotesResponse.Vote)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.GetAllVotesResponse.Vote)
    MergeFrom(*source);
  }
}

void GetAllVotesResponse_Vote::MergeFrom(const GetAllVotesResponse_Vote& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.GetAllVotesResponse.Vote)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.votename().size() > 0) {

    votename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.votename_);
  }
  if (from.voteid().size() > 0) {

    voteid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.voteid_);
  }
  if (from.isvalid().size() > 0) {

    isvalid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.isvalid_);
  }
}

void GetAllVotesResponse_Vote::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.GetAllVotesResponse.Vote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetAllVotesResponse_Vote::CopyFrom(const GetAllVotesResponse_Vote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.GetAllVotesResponse.Vote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetAllVotesResponse_Vote::IsInitialized() const {
  return true;
}

void GetAllVotesResponse_Vote::Swap(GetAllVotesResponse_Vote* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetAllVotesResponse_Vote::InternalSwap(GetAllVotesResponse_Vote* other) {
  using std::swap;
  votename_.Swap(&other->votename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  voteid_.Swap(&other->voteid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  isvalid_.Swap(&other->isvalid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetAllVotesResponse_Vote::GetMetadata() const {
  protobuf_getAllVotesResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getAllVotesResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetAllVotesResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetAllVotesResponse::kVotesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetAllVotesResponse::GetAllVotesResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_getAllVotesResponse_2eproto::scc_info_GetAllVotesResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.GetAllVotesResponse)
}
GetAllVotesResponse::GetAllVotesResponse(const GetAllVotesResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      votes_(from.votes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protoMsg.GetAllVotesResponse)
}

void GetAllVotesResponse::SharedCtor() {
}

GetAllVotesResponse::~GetAllVotesResponse() {
  // @@protoc_insertion_point(destructor:protoMsg.GetAllVotesResponse)
  SharedDtor();
}

void GetAllVotesResponse::SharedDtor() {
}

void GetAllVotesResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetAllVotesResponse::descriptor() {
  ::protobuf_getAllVotesResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getAllVotesResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetAllVotesResponse& GetAllVotesResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_getAllVotesResponse_2eproto::scc_info_GetAllVotesResponse.base);
  return *internal_default_instance();
}


void GetAllVotesResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.GetAllVotesResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  votes_.Clear();
  _internal_metadata_.Clear();
}

bool GetAllVotesResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.GetAllVotesResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .protoMsg.GetAllVotesResponse.Vote votes = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_votes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.GetAllVotesResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.GetAllVotesResponse)
  return false;
#undef DO_
}

void GetAllVotesResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.GetAllVotesResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protoMsg.GetAllVotesResponse.Vote votes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->votes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->votes(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.GetAllVotesResponse)
}

::google::protobuf::uint8* GetAllVotesResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.GetAllVotesResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protoMsg.GetAllVotesResponse.Vote votes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->votes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->votes(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.GetAllVotesResponse)
  return target;
}

size_t GetAllVotesResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.GetAllVotesResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .protoMsg.GetAllVotesResponse.Vote votes = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->votes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->votes(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetAllVotesResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.GetAllVotesResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetAllVotesResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetAllVotesResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.GetAllVotesResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.GetAllVotesResponse)
    MergeFrom(*source);
  }
}

void GetAllVotesResponse::MergeFrom(const GetAllVotesResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.GetAllVotesResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  votes_.MergeFrom(from.votes_);
}

void GetAllVotesResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.GetAllVotesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetAllVotesResponse::CopyFrom(const GetAllVotesResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.GetAllVotesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetAllVotesResponse::IsInitialized() const {
  return true;
}

void GetAllVotesResponse::Swap(GetAllVotesResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetAllVotesResponse::InternalSwap(GetAllVotesResponse* other) {
  using std::swap;
  CastToBase(&votes_)->InternalSwap(CastToBase(&other->votes_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetAllVotesResponse::GetMetadata() const {
  protobuf_getAllVotesResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getAllVotesResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protoMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::GetAllVotesResponse_Vote* Arena::CreateMaybeMessage< ::protoMsg::GetAllVotesResponse_Vote >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::GetAllVotesResponse_Vote >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::GetAllVotesResponse* Arena::CreateMaybeMessage< ::protoMsg::GetAllVotesResponse >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::GetAllVotesResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
