// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getVoteResultByOneJudge.proto

#include "getVoteResultByOneJudge.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protoMsg {
class GetVoteResultByOneJudgeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetVoteResultByOneJudge>
      _instance;
} _GetVoteResultByOneJudge_default_instance_;
}  // namespace protoMsg
namespace protobuf_getVoteResultByOneJudge_2eproto {
static void InitDefaultsGetVoteResultByOneJudge() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_GetVoteResultByOneJudge_default_instance_;
    new (ptr) ::protoMsg::GetVoteResultByOneJudge();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::GetVoteResultByOneJudge::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetVoteResultByOneJudge =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetVoteResultByOneJudge}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GetVoteResultByOneJudge.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudge, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudge, type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudge, uname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudge, ustatus_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protoMsg::GetVoteResultByOneJudge)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_GetVoteResultByOneJudge_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "getVoteResultByOneJudge.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035getVoteResultByOneJudge.proto\022\010protoMs"
      "g\"G\n\027GetVoteResultByOneJudge\022\014\n\004type\030\001 \001"
      "(\t\022\r\n\005uname\030\002 \001(\t\022\017\n\007ustatus\030\003 \001(\tb\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 122);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "getVoteResultByOneJudge.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_getVoteResultByOneJudge_2eproto
namespace protoMsg {

// ===================================================================

void GetVoteResultByOneJudge::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetVoteResultByOneJudge::kTypeFieldNumber;
const int GetVoteResultByOneJudge::kUnameFieldNumber;
const int GetVoteResultByOneJudge::kUstatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetVoteResultByOneJudge::GetVoteResultByOneJudge()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_getVoteResultByOneJudge_2eproto::scc_info_GetVoteResultByOneJudge.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.GetVoteResultByOneJudge)
}
GetVoteResultByOneJudge::GetVoteResultByOneJudge(const GetVoteResultByOneJudge& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.type().size() > 0) {
    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  uname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.uname().size() > 0) {
    uname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uname_);
  }
  ustatus_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.ustatus().size() > 0) {
    ustatus_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ustatus_);
  }
  // @@protoc_insertion_point(copy_constructor:protoMsg.GetVoteResultByOneJudge)
}

void GetVoteResultByOneJudge::SharedCtor() {
  type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ustatus_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetVoteResultByOneJudge::~GetVoteResultByOneJudge() {
  // @@protoc_insertion_point(destructor:protoMsg.GetVoteResultByOneJudge)
  SharedDtor();
}

void GetVoteResultByOneJudge::SharedDtor() {
  type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ustatus_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetVoteResultByOneJudge::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetVoteResultByOneJudge::descriptor() {
  ::protobuf_getVoteResultByOneJudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getVoteResultByOneJudge_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetVoteResultByOneJudge& GetVoteResultByOneJudge::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_getVoteResultByOneJudge_2eproto::scc_info_GetVoteResultByOneJudge.base);
  return *internal_default_instance();
}


void GetVoteResultByOneJudge::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.GetVoteResultByOneJudge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  uname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ustatus_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetVoteResultByOneJudge::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.GetVoteResultByOneJudge)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string type = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->type().data(), static_cast<int>(this->type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudge.type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string uname = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_uname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->uname().data(), static_cast<int>(this->uname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudge.uname"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string ustatus = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_ustatus()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->ustatus().data(), static_cast<int>(this->ustatus().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudge.ustatus"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.GetVoteResultByOneJudge)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.GetVoteResultByOneJudge)
  return false;
#undef DO_
}

void GetVoteResultByOneJudge::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.GetVoteResultByOneJudge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudge.type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->type(), output);
  }

  // string uname = 2;
  if (this->uname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->uname().data(), static_cast<int>(this->uname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudge.uname");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->uname(), output);
  }

  // string ustatus = 3;
  if (this->ustatus().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ustatus().data(), static_cast<int>(this->ustatus().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudge.ustatus");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->ustatus(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.GetVoteResultByOneJudge)
}

::google::protobuf::uint8* GetVoteResultByOneJudge::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.GetVoteResultByOneJudge)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string type = 1;
  if (this->type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->type().data(), static_cast<int>(this->type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudge.type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->type(), target);
  }

  // string uname = 2;
  if (this->uname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->uname().data(), static_cast<int>(this->uname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudge.uname");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->uname(), target);
  }

  // string ustatus = 3;
  if (this->ustatus().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->ustatus().data(), static_cast<int>(this->ustatus().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudge.ustatus");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->ustatus(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.GetVoteResultByOneJudge)
  return target;
}

size_t GetVoteResultByOneJudge::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.GetVoteResultByOneJudge)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string type = 1;
  if (this->type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->type());
  }

  // string uname = 2;
  if (this->uname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->uname());
  }

  // string ustatus = 3;
  if (this->ustatus().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->ustatus());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetVoteResultByOneJudge::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.GetVoteResultByOneJudge)
  GOOGLE_DCHECK_NE(&from, this);
  const GetVoteResultByOneJudge* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetVoteResultByOneJudge>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.GetVoteResultByOneJudge)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.GetVoteResultByOneJudge)
    MergeFrom(*source);
  }
}

void GetVoteResultByOneJudge::MergeFrom(const GetVoteResultByOneJudge& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.GetVoteResultByOneJudge)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.type().size() > 0) {

    type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.type_);
  }
  if (from.uname().size() > 0) {

    uname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.uname_);
  }
  if (from.ustatus().size() > 0) {

    ustatus_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.ustatus_);
  }
}

void GetVoteResultByOneJudge::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.GetVoteResultByOneJudge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetVoteResultByOneJudge::CopyFrom(const GetVoteResultByOneJudge& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.GetVoteResultByOneJudge)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetVoteResultByOneJudge::IsInitialized() const {
  return true;
}

void GetVoteResultByOneJudge::Swap(GetVoteResultByOneJudge* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetVoteResultByOneJudge::InternalSwap(GetVoteResultByOneJudge* other) {
  using std::swap;
  type_.Swap(&other->type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  uname_.Swap(&other->uname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  ustatus_.Swap(&other->ustatus_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetVoteResultByOneJudge::GetMetadata() const {
  protobuf_getVoteResultByOneJudge_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getVoteResultByOneJudge_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protoMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::GetVoteResultByOneJudge* Arena::CreateMaybeMessage< ::protoMsg::GetVoteResultByOneJudge >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::GetVoteResultByOneJudge >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
