// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: getVoteResultByOneJudgeResponse.proto

#include "getVoteResultByOneJudgeResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_getVoteResultByOneJudgeResponse_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_getVoteResultByOneJudgeResponse_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GetVoteResultByOneJudgeResponse_Vote;
}  // namespace protobuf_getVoteResultByOneJudgeResponse_2eproto
namespace protoMsg {
class GetVoteResultByOneJudgeResponse_VoteDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetVoteResultByOneJudgeResponse_Vote>
      _instance;
} _GetVoteResultByOneJudgeResponse_Vote_default_instance_;
class GetVoteResultByOneJudgeResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GetVoteResultByOneJudgeResponse>
      _instance;
} _GetVoteResultByOneJudgeResponse_default_instance_;
}  // namespace protoMsg
namespace protobuf_getVoteResultByOneJudgeResponse_2eproto {
static void InitDefaultsGetVoteResultByOneJudgeResponse_Vote() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_GetVoteResultByOneJudgeResponse_Vote_default_instance_;
    new (ptr) ::protoMsg::GetVoteResultByOneJudgeResponse_Vote();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::GetVoteResultByOneJudgeResponse_Vote::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GetVoteResultByOneJudgeResponse_Vote =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGetVoteResultByOneJudgeResponse_Vote}, {}};

static void InitDefaultsGetVoteResultByOneJudgeResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_GetVoteResultByOneJudgeResponse_default_instance_;
    new (ptr) ::protoMsg::GetVoteResultByOneJudgeResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::GetVoteResultByOneJudgeResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GetVoteResultByOneJudgeResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGetVoteResultByOneJudgeResponse}, {
      &protobuf_getVoteResultByOneJudgeResponse_2eproto::scc_info_GetVoteResultByOneJudgeResponse_Vote.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GetVoteResultByOneJudgeResponse_Vote.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GetVoteResultByOneJudgeResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse_Vote, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse_Vote, votename_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse_Vote, voteid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse_Vote, isvalid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse_Vote, isvoted_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::GetVoteResultByOneJudgeResponse, votes_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protoMsg::GetVoteResultByOneJudgeResponse_Vote)},
  { 9, -1, sizeof(::protoMsg::GetVoteResultByOneJudgeResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_GetVoteResultByOneJudgeResponse_Vote_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_GetVoteResultByOneJudgeResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "getVoteResultByOneJudgeResponse.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n%getVoteResultByOneJudgeResponse.proto\022"
      "\010protoMsg\"\254\001\n\037GetVoteResultByOneJudgeRes"
      "ponse\022=\n\005votes\030\001 \003(\0132..protoMsg.GetVoteR"
      "esultByOneJudgeResponse.Vote\032J\n\004Vote\022\020\n\010"
      "voteName\030\001 \001(\t\022\016\n\006voteID\030\002 \001(\t\022\017\n\007isVali"
      "d\030\003 \001(\t\022\017\n\007isVoted\030\004 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 232);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "getVoteResultByOneJudgeResponse.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_getVoteResultByOneJudgeResponse_2eproto
namespace protoMsg {

// ===================================================================

void GetVoteResultByOneJudgeResponse_Vote::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetVoteResultByOneJudgeResponse_Vote::kVoteNameFieldNumber;
const int GetVoteResultByOneJudgeResponse_Vote::kVoteIDFieldNumber;
const int GetVoteResultByOneJudgeResponse_Vote::kIsValidFieldNumber;
const int GetVoteResultByOneJudgeResponse_Vote::kIsVotedFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetVoteResultByOneJudgeResponse_Vote::GetVoteResultByOneJudgeResponse_Vote()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_getVoteResultByOneJudgeResponse_2eproto::scc_info_GetVoteResultByOneJudgeResponse_Vote.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
}
GetVoteResultByOneJudgeResponse_Vote::GetVoteResultByOneJudgeResponse_Vote(const GetVoteResultByOneJudgeResponse_Vote& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  votename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.votename().size() > 0) {
    votename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.votename_);
  }
  voteid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.voteid().size() > 0) {
    voteid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.voteid_);
  }
  isvalid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.isvalid().size() > 0) {
    isvalid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.isvalid_);
  }
  isvoted_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.isvoted().size() > 0) {
    isvoted_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.isvoted_);
  }
  // @@protoc_insertion_point(copy_constructor:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
}

void GetVoteResultByOneJudgeResponse_Vote::SharedCtor() {
  votename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  voteid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvalid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvoted_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GetVoteResultByOneJudgeResponse_Vote::~GetVoteResultByOneJudgeResponse_Vote() {
  // @@protoc_insertion_point(destructor:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  SharedDtor();
}

void GetVoteResultByOneJudgeResponse_Vote::SharedDtor() {
  votename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  voteid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvalid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvoted_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GetVoteResultByOneJudgeResponse_Vote::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetVoteResultByOneJudgeResponse_Vote::descriptor() {
  ::protobuf_getVoteResultByOneJudgeResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getVoteResultByOneJudgeResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetVoteResultByOneJudgeResponse_Vote& GetVoteResultByOneJudgeResponse_Vote::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_getVoteResultByOneJudgeResponse_2eproto::scc_info_GetVoteResultByOneJudgeResponse_Vote.base);
  return *internal_default_instance();
}


void GetVoteResultByOneJudgeResponse_Vote::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  votename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  voteid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvalid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isvoted_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GetVoteResultByOneJudgeResponse_Vote::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string voteName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_votename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->votename().data(), static_cast<int>(this->votename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudgeResponse.Vote.voteName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string voteID = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_voteid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->voteid().data(), static_cast<int>(this->voteid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudgeResponse.Vote.voteID"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string isValid = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_isvalid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->isvalid().data(), static_cast<int>(this->isvalid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudgeResponse.Vote.isValid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string isVoted = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_isvoted()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->isvoted().data(), static_cast<int>(this->isvoted().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.GetVoteResultByOneJudgeResponse.Vote.isVoted"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  return false;
#undef DO_
}

void GetVoteResultByOneJudgeResponse_Vote::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string voteName = 1;
  if (this->votename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->votename().data(), static_cast<int>(this->votename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.voteName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->votename(), output);
  }

  // string voteID = 2;
  if (this->voteid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->voteid().data(), static_cast<int>(this->voteid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.voteID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->voteid(), output);
  }

  // string isValid = 3;
  if (this->isvalid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->isvalid().data(), static_cast<int>(this->isvalid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.isValid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->isvalid(), output);
  }

  // string isVoted = 4;
  if (this->isvoted().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->isvoted().data(), static_cast<int>(this->isvoted().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.isVoted");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->isvoted(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
}

::google::protobuf::uint8* GetVoteResultByOneJudgeResponse_Vote::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string voteName = 1;
  if (this->votename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->votename().data(), static_cast<int>(this->votename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.voteName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->votename(), target);
  }

  // string voteID = 2;
  if (this->voteid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->voteid().data(), static_cast<int>(this->voteid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.voteID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->voteid(), target);
  }

  // string isValid = 3;
  if (this->isvalid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->isvalid().data(), static_cast<int>(this->isvalid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.isValid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->isvalid(), target);
  }

  // string isVoted = 4;
  if (this->isvoted().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->isvoted().data(), static_cast<int>(this->isvoted().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.GetVoteResultByOneJudgeResponse.Vote.isVoted");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->isvoted(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  return target;
}

size_t GetVoteResultByOneJudgeResponse_Vote::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string voteName = 1;
  if (this->votename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->votename());
  }

  // string voteID = 2;
  if (this->voteid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->voteid());
  }

  // string isValid = 3;
  if (this->isvalid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->isvalid());
  }

  // string isVoted = 4;
  if (this->isvoted().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->isvoted());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetVoteResultByOneJudgeResponse_Vote::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  GOOGLE_DCHECK_NE(&from, this);
  const GetVoteResultByOneJudgeResponse_Vote* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetVoteResultByOneJudgeResponse_Vote>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
    MergeFrom(*source);
  }
}

void GetVoteResultByOneJudgeResponse_Vote::MergeFrom(const GetVoteResultByOneJudgeResponse_Vote& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.votename().size() > 0) {

    votename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.votename_);
  }
  if (from.voteid().size() > 0) {

    voteid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.voteid_);
  }
  if (from.isvalid().size() > 0) {

    isvalid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.isvalid_);
  }
  if (from.isvoted().size() > 0) {

    isvoted_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.isvoted_);
  }
}

void GetVoteResultByOneJudgeResponse_Vote::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetVoteResultByOneJudgeResponse_Vote::CopyFrom(const GetVoteResultByOneJudgeResponse_Vote& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.GetVoteResultByOneJudgeResponse.Vote)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetVoteResultByOneJudgeResponse_Vote::IsInitialized() const {
  return true;
}

void GetVoteResultByOneJudgeResponse_Vote::Swap(GetVoteResultByOneJudgeResponse_Vote* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetVoteResultByOneJudgeResponse_Vote::InternalSwap(GetVoteResultByOneJudgeResponse_Vote* other) {
  using std::swap;
  votename_.Swap(&other->votename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  voteid_.Swap(&other->voteid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  isvalid_.Swap(&other->isvalid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  isvoted_.Swap(&other->isvoted_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetVoteResultByOneJudgeResponse_Vote::GetMetadata() const {
  protobuf_getVoteResultByOneJudgeResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getVoteResultByOneJudgeResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void GetVoteResultByOneJudgeResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GetVoteResultByOneJudgeResponse::kVotesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GetVoteResultByOneJudgeResponse::GetVoteResultByOneJudgeResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_getVoteResultByOneJudgeResponse_2eproto::scc_info_GetVoteResultByOneJudgeResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.GetVoteResultByOneJudgeResponse)
}
GetVoteResultByOneJudgeResponse::GetVoteResultByOneJudgeResponse(const GetVoteResultByOneJudgeResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      votes_(from.votes_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protoMsg.GetVoteResultByOneJudgeResponse)
}

void GetVoteResultByOneJudgeResponse::SharedCtor() {
}

GetVoteResultByOneJudgeResponse::~GetVoteResultByOneJudgeResponse() {
  // @@protoc_insertion_point(destructor:protoMsg.GetVoteResultByOneJudgeResponse)
  SharedDtor();
}

void GetVoteResultByOneJudgeResponse::SharedDtor() {
}

void GetVoteResultByOneJudgeResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GetVoteResultByOneJudgeResponse::descriptor() {
  ::protobuf_getVoteResultByOneJudgeResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getVoteResultByOneJudgeResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GetVoteResultByOneJudgeResponse& GetVoteResultByOneJudgeResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_getVoteResultByOneJudgeResponse_2eproto::scc_info_GetVoteResultByOneJudgeResponse.base);
  return *internal_default_instance();
}


void GetVoteResultByOneJudgeResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.GetVoteResultByOneJudgeResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  votes_.Clear();
  _internal_metadata_.Clear();
}

bool GetVoteResultByOneJudgeResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.GetVoteResultByOneJudgeResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .protoMsg.GetVoteResultByOneJudgeResponse.Vote votes = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_votes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.GetVoteResultByOneJudgeResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.GetVoteResultByOneJudgeResponse)
  return false;
#undef DO_
}

void GetVoteResultByOneJudgeResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.GetVoteResultByOneJudgeResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protoMsg.GetVoteResultByOneJudgeResponse.Vote votes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->votes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->votes(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.GetVoteResultByOneJudgeResponse)
}

::google::protobuf::uint8* GetVoteResultByOneJudgeResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.GetVoteResultByOneJudgeResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protoMsg.GetVoteResultByOneJudgeResponse.Vote votes = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->votes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->votes(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.GetVoteResultByOneJudgeResponse)
  return target;
}

size_t GetVoteResultByOneJudgeResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.GetVoteResultByOneJudgeResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .protoMsg.GetVoteResultByOneJudgeResponse.Vote votes = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->votes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->votes(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GetVoteResultByOneJudgeResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.GetVoteResultByOneJudgeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const GetVoteResultByOneJudgeResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GetVoteResultByOneJudgeResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.GetVoteResultByOneJudgeResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.GetVoteResultByOneJudgeResponse)
    MergeFrom(*source);
  }
}

void GetVoteResultByOneJudgeResponse::MergeFrom(const GetVoteResultByOneJudgeResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.GetVoteResultByOneJudgeResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  votes_.MergeFrom(from.votes_);
}

void GetVoteResultByOneJudgeResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.GetVoteResultByOneJudgeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GetVoteResultByOneJudgeResponse::CopyFrom(const GetVoteResultByOneJudgeResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.GetVoteResultByOneJudgeResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GetVoteResultByOneJudgeResponse::IsInitialized() const {
  return true;
}

void GetVoteResultByOneJudgeResponse::Swap(GetVoteResultByOneJudgeResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GetVoteResultByOneJudgeResponse::InternalSwap(GetVoteResultByOneJudgeResponse* other) {
  using std::swap;
  CastToBase(&votes_)->InternalSwap(CastToBase(&other->votes_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GetVoteResultByOneJudgeResponse::GetMetadata() const {
  protobuf_getVoteResultByOneJudgeResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_getVoteResultByOneJudgeResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protoMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::GetVoteResultByOneJudgeResponse_Vote* Arena::CreateMaybeMessage< ::protoMsg::GetVoteResultByOneJudgeResponse_Vote >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::GetVoteResultByOneJudgeResponse_Vote >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::GetVoteResultByOneJudgeResponse* Arena::CreateMaybeMessage< ::protoMsg::GetVoteResultByOneJudgeResponse >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::GetVoteResultByOneJudgeResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
