// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: voteResponse.proto

#include "voteResponse.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_voteResponse_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_voteResponse_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_VoteResponse_Plaerscore;
}  // namespace protobuf_voteResponse_2eproto
namespace protoMsg {
class VoteResponse_PlaerscoreDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VoteResponse_Plaerscore>
      _instance;
} _VoteResponse_Plaerscore_default_instance_;
class VoteResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<VoteResponse>
      _instance;
} _VoteResponse_default_instance_;
}  // namespace protoMsg
namespace protobuf_voteResponse_2eproto {
static void InitDefaultsVoteResponse_Plaerscore() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_VoteResponse_Plaerscore_default_instance_;
    new (ptr) ::protoMsg::VoteResponse_Plaerscore();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::VoteResponse_Plaerscore::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_VoteResponse_Plaerscore =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsVoteResponse_Plaerscore}, {}};

static void InitDefaultsVoteResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::protoMsg::_VoteResponse_default_instance_;
    new (ptr) ::protoMsg::VoteResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::protoMsg::VoteResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_VoteResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsVoteResponse}, {
      &protobuf_voteResponse_2eproto::scc_info_VoteResponse_Plaerscore.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_VoteResponse_Plaerscore.base);
  ::google::protobuf::internal::InitSCC(&scc_info_VoteResponse.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::VoteResponse_Plaerscore, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::VoteResponse_Plaerscore, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::VoteResponse_Plaerscore, score_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::VoteResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::protoMsg::VoteResponse, playerscores_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::protoMsg::VoteResponse_Plaerscore)},
  { 7, -1, sizeof(::protoMsg::VoteResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_VoteResponse_Plaerscore_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::protoMsg::_VoteResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "voteResponse.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022voteResponse.proto\022\010protoMsg\"r\n\014VoteRe"
      "sponse\0227\n\014playerScores\030\001 \003(\0132!.protoMsg."
      "VoteResponse.Plaerscore\032)\n\nPlaerscore\022\014\n"
      "\004name\030\001 \001(\t\022\r\n\005score\030\002 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 154);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "voteResponse.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_voteResponse_2eproto
namespace protoMsg {

// ===================================================================

void VoteResponse_Plaerscore::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VoteResponse_Plaerscore::kNameFieldNumber;
const int VoteResponse_Plaerscore::kScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VoteResponse_Plaerscore::VoteResponse_Plaerscore()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_voteResponse_2eproto::scc_info_VoteResponse_Plaerscore.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.VoteResponse.Plaerscore)
}
VoteResponse_Plaerscore::VoteResponse_Plaerscore(const VoteResponse_Plaerscore& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  score_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.score().size() > 0) {
    score_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.score_);
  }
  // @@protoc_insertion_point(copy_constructor:protoMsg.VoteResponse.Plaerscore)
}

void VoteResponse_Plaerscore::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  score_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

VoteResponse_Plaerscore::~VoteResponse_Plaerscore() {
  // @@protoc_insertion_point(destructor:protoMsg.VoteResponse.Plaerscore)
  SharedDtor();
}

void VoteResponse_Plaerscore::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  score_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void VoteResponse_Plaerscore::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VoteResponse_Plaerscore::descriptor() {
  ::protobuf_voteResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voteResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VoteResponse_Plaerscore& VoteResponse_Plaerscore::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_voteResponse_2eproto::scc_info_VoteResponse_Plaerscore.base);
  return *internal_default_instance();
}


void VoteResponse_Plaerscore::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.VoteResponse.Plaerscore)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  score_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool VoteResponse_Plaerscore::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.VoteResponse.Plaerscore)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.VoteResponse.Plaerscore.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string score = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_score()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->score().data(), static_cast<int>(this->score().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "protoMsg.VoteResponse.Plaerscore.score"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.VoteResponse.Plaerscore)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.VoteResponse.Plaerscore)
  return false;
#undef DO_
}

void VoteResponse_Plaerscore::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.VoteResponse.Plaerscore)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.VoteResponse.Plaerscore.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string score = 2;
  if (this->score().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->score().data(), static_cast<int>(this->score().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.VoteResponse.Plaerscore.score");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->score(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.VoteResponse.Plaerscore)
}

::google::protobuf::uint8* VoteResponse_Plaerscore::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.VoteResponse.Plaerscore)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.VoteResponse.Plaerscore.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string score = 2;
  if (this->score().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->score().data(), static_cast<int>(this->score().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "protoMsg.VoteResponse.Plaerscore.score");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->score(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.VoteResponse.Plaerscore)
  return target;
}

size_t VoteResponse_Plaerscore::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.VoteResponse.Plaerscore)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string score = 2;
  if (this->score().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->score());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VoteResponse_Plaerscore::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.VoteResponse.Plaerscore)
  GOOGLE_DCHECK_NE(&from, this);
  const VoteResponse_Plaerscore* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VoteResponse_Plaerscore>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.VoteResponse.Plaerscore)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.VoteResponse.Plaerscore)
    MergeFrom(*source);
  }
}

void VoteResponse_Plaerscore::MergeFrom(const VoteResponse_Plaerscore& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.VoteResponse.Plaerscore)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.score().size() > 0) {

    score_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.score_);
  }
}

void VoteResponse_Plaerscore::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.VoteResponse.Plaerscore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VoteResponse_Plaerscore::CopyFrom(const VoteResponse_Plaerscore& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.VoteResponse.Plaerscore)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VoteResponse_Plaerscore::IsInitialized() const {
  return true;
}

void VoteResponse_Plaerscore::Swap(VoteResponse_Plaerscore* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VoteResponse_Plaerscore::InternalSwap(VoteResponse_Plaerscore* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  score_.Swap(&other->score_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VoteResponse_Plaerscore::GetMetadata() const {
  protobuf_voteResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voteResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void VoteResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int VoteResponse::kPlayerScoresFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

VoteResponse::VoteResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_voteResponse_2eproto::scc_info_VoteResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:protoMsg.VoteResponse)
}
VoteResponse::VoteResponse(const VoteResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      playerscores_(from.playerscores_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:protoMsg.VoteResponse)
}

void VoteResponse::SharedCtor() {
}

VoteResponse::~VoteResponse() {
  // @@protoc_insertion_point(destructor:protoMsg.VoteResponse)
  SharedDtor();
}

void VoteResponse::SharedDtor() {
}

void VoteResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* VoteResponse::descriptor() {
  ::protobuf_voteResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voteResponse_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const VoteResponse& VoteResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_voteResponse_2eproto::scc_info_VoteResponse.base);
  return *internal_default_instance();
}


void VoteResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:protoMsg.VoteResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  playerscores_.Clear();
  _internal_metadata_.Clear();
}

bool VoteResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:protoMsg.VoteResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .protoMsg.VoteResponse.Plaerscore playerScores = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_playerscores()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:protoMsg.VoteResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:protoMsg.VoteResponse)
  return false;
#undef DO_
}

void VoteResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:protoMsg.VoteResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protoMsg.VoteResponse.Plaerscore playerScores = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->playerscores_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->playerscores(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:protoMsg.VoteResponse)
}

::google::protobuf::uint8* VoteResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:protoMsg.VoteResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .protoMsg.VoteResponse.Plaerscore playerScores = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->playerscores_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->playerscores(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:protoMsg.VoteResponse)
  return target;
}

size_t VoteResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:protoMsg.VoteResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .protoMsg.VoteResponse.Plaerscore playerScores = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->playerscores_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->playerscores(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void VoteResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:protoMsg.VoteResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const VoteResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const VoteResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:protoMsg.VoteResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:protoMsg.VoteResponse)
    MergeFrom(*source);
  }
}

void VoteResponse::MergeFrom(const VoteResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:protoMsg.VoteResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  playerscores_.MergeFrom(from.playerscores_);
}

void VoteResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:protoMsg.VoteResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void VoteResponse::CopyFrom(const VoteResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:protoMsg.VoteResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool VoteResponse::IsInitialized() const {
  return true;
}

void VoteResponse::Swap(VoteResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void VoteResponse::InternalSwap(VoteResponse* other) {
  using std::swap;
  CastToBase(&playerscores_)->InternalSwap(CastToBase(&other->playerscores_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata VoteResponse::GetMetadata() const {
  protobuf_voteResponse_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_voteResponse_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protoMsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::VoteResponse_Plaerscore* Arena::CreateMaybeMessage< ::protoMsg::VoteResponse_Plaerscore >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::VoteResponse_Plaerscore >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::protoMsg::VoteResponse* Arena::CreateMaybeMessage< ::protoMsg::VoteResponse >(Arena* arena) {
  return Arena::CreateInternal< ::protoMsg::VoteResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
